"""
Name: Nishanth
Description: dice simulator
Date: 18th March 2022
Time: 8:44
"""

import random
import turtle

 
t=turtle.Screen()
turtle.speed(10000)
turtle.pensize(5)

x = random.randint(1,6)
print(x)

turtle.penup()
turtle.goto(-300, 300)
turtle.pendown()
turtle.color('black')

turtle.forward(600)
turtle.right(90)
turtle.forward(600)
turtle.right(90)
turtle.forward(600)
turtle.right(90)
turtle.forward(600)
turtle.right(90)

if x ==1:
    turtle.penup()
    turtle.goto(0,0)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()
elif x==2: 
    turtle.penup()
    turtle.goto(-50, 5)
    turtle.pendown()
    turtle.color('black', 'black') 
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(50, 5)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()   

elif x==3: 
    turtle.penup()
    turtle.goto(-100, 50)
    turtle.pendown()
    turtle.color('black', 'black') 
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(100, 50)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()  
    turtle.penup()
    turtle.goto(0, -50)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()  

elif x==4: 
    turtle.penup()
    turtle.goto(-100, 50)
    turtle.pendown()
    turtle.color('black', 'black') 
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()

    turtle.penup()
    turtle.goto(100, 50)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill() 

    turtle.penup()
    turtle.goto(-100, -100)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()

    turtle.penup()
    turtle.goto(100, -100)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()

elif x==5: 
    turtle.penup()
    turtle.goto(-100, 50)
    turtle.pendown()
    turtle.color('black', 'black') 
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()

    turtle.penup()
    turtle.goto(100, 50)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill() 

    turtle.penup()
    turtle.goto(-100, -100)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()

    turtle.penup()
    turtle.goto(100, -100)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill() 

    turtle.penup()
    turtle.goto(0, 200)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()   

elif x==6: 
    turtle.penup()
    turtle.goto(-100, 50)
    turtle.pendown()
    turtle.color('black', 'black') 
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()

    turtle.penup()
    turtle.goto(100, 50)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill() 

    turtle.penup()
    turtle.goto(-100, -100)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()

    turtle.penup()
    turtle.goto(100, -100)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill() 

    turtle.penup()
    turtle.goto(-100, 200)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()   

    turtle.penup()
    turtle.goto(100, 200)
    turtle.pendown()
    turtle.color('black', 'black')
    turtle.begin_fill()
    turtle.circle(45)
    turtle.end_fill()     

t.exitonclick()